# Generated by Django 5.0.2 on 2024-03-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomWebApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.IntegerField(blank=True, default=1234567890),
            preserve_default=False,
        ),
    ]
