# Generated by Django 5.0.2 on 2024-03-03 11:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomWebApp', '0006_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.CharField(default=uuid.uuid4, max_length=50, unique=True),
        ),
    ]
