# Generated by Django 5.0.2 on 2024-03-03 22:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomWebApp', '0012_cartproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='slug',
            field=models.CharField(default=uuid.uuid4, max_length=50, unique=True),
        ),
    ]
